10 TEXT: SPEED=255
20 PRINT "VERASDEDIT - VERA SD SECTOR EDITOR"
30 PRINT "BY ANOMIXER"
40 PRINT "-----------------------------"
50 PRINT
60 PRINT "READING SECTOR..."
100 PRINT CHR$(4);"BRUN VERASDEDIT.BIN"
